### ISSUE TITLE
context.WithFactory() fails with static factory methods

### ISSUE THREAD

**Issue by schuettecarsten** [z4kn4fein/stashbox#59]
The following service registration generates an error on resolving in 2.7.5 when the factory method is static:

```				
context.WithFactory(staticFactoryMethod)
	.WithSingletonLifetime()
	.WithoutDisposalTracking();
```

This works fine with 2.7.4.

**Comment by z4kn4fein** [comment]
Hey, thanks for reporting this, I'll fix it in the next few days

**Comment by z4kn4fein** [comment]
Fixed in v2.7.6

**Comment by schuettecarsten** [comment]
Next few days and a fix within 9 hours, Great work! :-D

**Comment by schuettecarsten** [comment]
I still get the exception with v2.7.6.

```
System.Core.dll!System.Linq.Expressions.Expression.ValidateArgumentCount(System.Reflection.MethodBase method, System.Linq.Expressions.ExpressionType nodeKind, int count, System.Reflection.ParameterInfo[] pis)	Unknown
System.Core.dll!System.Linq.Expressions.Expression.ValidateArgumentTypes(System.Reflection.MethodBase method, System.Linq.Expressions.ExpressionType nodeKind, ref System.Collections.ObjectModel.ReadOnlyCollection<System.Linq.Expressions.Expression> arguments)	Unknown
System.Core.dll!System.Linq.Expressions.Expression.Call(System.Linq.Expressions.Expression instance, System.Reflection.MethodInfo method, System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)	Unknown
Stashbox.dll!Stashbox.BuildUp.FactoryObjectBuilder.GetExpressionInternal(Stashbox.IContainerContext containerContext, Stashbox.Registration.IServiceRegistration serviceRegistration, Stashbox.Resolution.ResolutionContext resolutionContext, System.Type resolveType)	Unknown
Stashbox.dll!Stashbox.BuildUp.ObjectBuilderBase.BuildDisposalTrackingAndFinalizerExpression(Stashbox.IContainerContext containerContext, Stashbox.Registration.IServiceRegistration serviceRegistration, Stashbox.Resolution.ResolutionContext resolutionContext, System.Type resolveType)	Unknown
Stashbox.dll!Stashbox.BuildUp.ObjectBuilderBase.GetExpression(Stashbox.IContainerContext containerContext, Stashbox.Registration.IServiceRegistration serviceRegistration, Stashbox.Resolution.ResolutionContext resolutionContext, System.Type resolveType)	Unknown
Stashbox.dll!Stashbox.Lifetime.SingletonLifetime.GetExpression(Stashbox.IContainerContext containerContext, Stashbox.Registration.IServiceRegistration serviceRegistration, Stashbox.BuildUp.IObjectBuilder objectBuilder, Stashbox.Resolution.ResolutionContext resolutionContext, System.Type resolveType)	Unknown
Stashbox.dll!Stashbox.Registration.ServiceRegistration.ConstructExpression(Stashbox.IContainerContext containerContext, Stashbox.Resolution.ResolutionContext resolutionContext, System.Type resolveType)	Unknown
Stashbox.dll!Stashbox.Registration.ServiceRegistration.GetExpression(Stashbox.IContainerContext containerContext, Stashbox.Resolution.ResolutionContext resolutionContext, System.Type resolveType)	Unknown
Stashbox.dll!Stashbox.ResolutionScope.Activate(Stashbox.Resolution.ResolutionContext resolutionContext, System.Type type, object name)	Unknown
Stashbox.dll!Stashbox.ResolutionScope.Resolve(System.Type typeFrom, bool nullResultAllowed, object[] dependencyOverrides)	Unknown
Stashbox.dll!Stashbox.StashboxContainer.Resolve(System.Type typeFrom, bool nullResultAllowed, object[] dependencyOverrides)	Unknown
Stashbox.dll!Stashbox.DependencyResolverExtensions.Resolve<CmtDbContextFactory>(Stashbox.IDependencyResolver resolver, bool nullResultAllowed, object[] dependencyOverrides)	Unknown
```
I use the following code to register the service/factory method:
```
	var memberExpr = Expression.MakeMemberAccess(null, propertyInfo);
	var lambdaExpr = Expression.Lambda<Func<object>>(memberExpr);

	context
		.WithFactory(lambdaExpr.Compile())
		.WithSingletonLifetime()
		.WithoutDisposalTracking();
```

**Comment by z4kn4fein** [comment]
Uh, sorry, let me check again with this spec

**Comment by z4kn4fein** [comment]
Hey, I pushed a new version to my [pre-release feed](https://www.myget.org/feed/pcsajtai/package/nuget/Stashbox) with the fix, could you please try it again?

**Comment by schuettecarsten** [comment]
The issue is fixed in the prerelease version. Thank you.
Interesting how to find out if a method is a compiled Lambda statement....

**Comment by z4kn4fein** [comment]
Cool!
Yeah, it's interesting, I did not find any other way yet which could determine that it's a compiled lambda, but I'll continue the search. More tests to make this solution solid and then I'll publish it today or tomorrow.

**Comment by z4kn4fein** [comment]
Fixed in [v2.7.8](https://github.com/z4kn4fein/stashbox/releases/tag/2.7.8)
